name: Zip src folder and add to repo

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip src folder
      run: |
        echo "Creating new src.zip from src folder... 🔒"
        mkdir -p build
        zip -r -X build/src.zip src
        echo "Zip created 🚀"

    - name: Create new branch and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Create new branch
        git checkout -b branch-${{ github.sha }}

        git add build/src.zip
        git commit -m "chore(ci): generate zip bundle"
        git push origin branch-${{ github.sha }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "chore(ci): generate zip bundle"
        body: "Generated new src.zip"
        branch: "branch-${{ github.sha }}"
        base: "master"
